FROM ctfd/ctfd
USER root
RUN pip install -r development.txt -i https://mirrors.aliyun.com/pypi/simple
COPY . CTFd/plugins/ctfd-whale
RUN pip install -r CTFd/plugins/ctfd-whale/requirements.txt -i https://mirrors.aliyun.com/pypi/simple
